# Generated by Django 3.0.7 on 2020-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200704_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
