# Generated by Django 3.0.7 on 2020-07-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200704_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
