# Generated by Django 3.0.7 on 2020-07-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200704_2225'),
        ('restaurants', '0005_restaurant_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Food')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.YoutubeReview')),
            ],
        ),
    ]
