# Generated by Django 3.0.7 on 2020-07-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200704_2225'),
        ('restaurants', '0007_remove_food_youtube_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='youtube_review',
        ),
        migrations.CreateModel(
            name='RestaurantYoutubeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.YoutubeReview')),
            ],
        ),
    ]
