# Generated by Django 3.0.7 on 2020-07-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_area_city_youtubereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='area_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('area_name', 'city')},
        ),
    ]
